from repo_vendor.readme_gen import (
    build_vended_readme,
    has_readme_placeholders,
    render_template_readme,
    resolve_vended_readme,
)


def test_vended_readme_is_project_not_template():
    text = build_vended_readme(
        repo_name="billing-gateway",
        summary="Billing gateway service",
        description="Handles invoices for EU",
        issue_key="KAN-42",
        template="template-generic-repo",
        repo_url="https://github.com/pete-leese/billing-gateway",
    )
    assert text.startswith("# billing-gateway")
    assert "KAN-42" in text
    assert "Handles invoices" in text
    assert "template-generic-repo" in text
    assert "Python repository template" not in text
    assert "Boilerplate for" not in text


def test_render_template_readme_preserves_terraform_docs_markers():
    template = """# {{REPO_NAME}}

{{DESCRIPTION}}

## Origin

- **Jira:** `{{ISSUE_KEY}}`
- **Summary:** {{SUMMARY}}
- **Created from template:** `{{TEMPLATE}}`
- **Repository:** {{REPO_URL}}

## Terraform docs

<!-- BEGIN_TF_DOCS -->
Placeholder — regenerated by terraform-docs.
<!-- END_TF_DOCS -->
"""
    assert has_readme_placeholders(template)
    out = render_template_readme(
        template,
        repo_name="terraform-module-gke-gcp",
        summary="GKE module",
        description="Reusable GKE module",
        issue_key="REPO-15",
        template="template-terraform-repo",
        repo_url="https://github.com/pete-leese/terraform-module-gke-gcp",
    )
    assert out.startswith("# terraform-module-gke-gcp")
    assert "{{REPO_NAME}}" not in out
    assert "REPO-15" in out
    assert "<!-- BEGIN_TF_DOCS -->" in out
    assert "<!-- END_TF_DOCS -->" in out
    assert "Placeholder — regenerated by terraform-docs." in out


def test_resolve_falls_back_without_placeholders():
    legacy = "# Old template\n\nBoilerplate only.\n"
    out = resolve_vended_readme(
        legacy,
        repo_name="billing-gateway",
        summary="Billing",
        description="desc",
        issue_key="KAN-1",
        template="template-generic-repo",
        repo_url="https://github.com/example/billing-gateway",
    )
    assert out.startswith("# billing-gateway")
    assert "Boilerplate only" not in out
